### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Amel337** [SlowLifeRP/Bugtracker#2]
Hi wenn eine Tote Person stabilisiert wurde und wir medics die dann hoch holen dann kriegen wir den gleichen dispatch obwohl die person nicht gestorben ist sondern wiederbelebt wurde.
Discord- Peter Griffin#2308

**Comment by Janisbtw** [comment]
Sollte behoben sein

**Comment by Amel337** [comment]
Ja ist es danke 👍
