### ISSUE TITLE
Bugreport / Methroute

### ISSUE THREAD

**Issue by Maxzoner1** [SlowLifeRP/Bugtracker#9]
Hallo, hier wollte ich mal einen Bug melden. Da ich kein **_Meth_** aufsammeln kann, b.z.w auch von **_niemanden kriegen_** kann stellt sich Mir nun die Frage woran liegt das. Ich habe schon im Support auf Antworten gehofft, aber das war auch vergebens. Nun erstelle ich einfach mal ein Ticket, um zu gucken ob sich denn nicht doch noch einer mal bei Mir meldet und mir mit diesen Thema hilft. Mit freundlichen Grüßen Jackson Crest aka GomorrhaUP

**Comment by Janisbtw** [comment]
Wie heißt du auf Steam

**Comment by Maxzoner1** [comment]
Max

**Comment by Janisbtw** [comment]
Ist behoben
